// Code generated by Sphere. DO NOT EDIT.
package render

import (
	"github.com/go-sphere/sphere-layout/api/entpb"
	sharedv1 "github.com/go-sphere/sphere-layout/api/shared/v1"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/ent"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/ent/admin"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/ent/adminsession"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/ent/keyvaluestore"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/ent/user"
	"github.com/go-sphere/sphere/database/bind"
)

func CreateAdmin(source *ent.AdminCreate, target *entpb.Admin, options ...bind.Option) *ent.AdminCreate {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(admin.FieldID) {
		if option.CanSetZero(admin.FieldID) || target.Id != 0 {
			source.SetID(target.Id)
		}
	}
	if option.CanSetField(admin.FieldUsername) {
		if option.CanSetZero(admin.FieldUsername) || target.Username != "" {
			source.SetUsername(target.Username)
		}
	}
	if option.CanSetField(admin.FieldNickname) {
		if option.CanSetZero(admin.FieldNickname) || target.Nickname != "" {
			source.SetNickname(target.Nickname)
		}
	}
	if option.CanSetField(admin.FieldAvatar) {
		if option.CanSetZero(admin.FieldAvatar) || target.Avatar != "" {
			source.SetAvatar(target.Avatar)
		}
	}
	if option.CanSetField(admin.FieldPassword) {
		if option.CanSetZero(admin.FieldPassword) || target.Password != "" {
			source.SetPassword(target.Password)
		}
	}
	if option.CanSetField(admin.FieldRoles) {
		if option.CanSetZero(admin.FieldRoles) || target.Roles != nil {
			source.SetRoles(target.Roles)
		}
	}
	return source
}

func UpdateOneAdmin(source *ent.AdminUpdateOne, target *entpb.Admin, options ...bind.Option) *ent.AdminUpdateOne {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(admin.FieldUsername) {
		if option.CanSetZero(admin.FieldUsername) || target.Username != "" {
			source.SetUsername(target.Username)
		}
	}
	if option.CanSetField(admin.FieldNickname) {
		if option.CanSetZero(admin.FieldNickname) || target.Nickname != "" {
			source.SetNickname(target.Nickname)
		}
	}
	if option.CanSetField(admin.FieldAvatar) {
		if option.CanSetZero(admin.FieldAvatar) || target.Avatar != "" {
			source.SetAvatar(target.Avatar)
		}
	}
	if option.CanSetField(admin.FieldPassword) {
		if option.CanSetZero(admin.FieldPassword) || target.Password != "" {
			source.SetPassword(target.Password)
		}
	}
	if option.CanSetField(admin.FieldRoles) {
		if option.CanSetZero(admin.FieldRoles) || target.Roles != nil {
			source.SetRoles(target.Roles)
		}
	}
	return source
}

func CreateAdminSession(source *ent.AdminSessionCreate, target *entpb.AdminSession, options ...bind.Option) *ent.AdminSessionCreate {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(adminsession.FieldID) {
		if option.CanSetZero(adminsession.FieldID) || target.Id != 0 {
			source.SetID(target.Id)
		}
	}
	if option.CanSetField(adminsession.FieldUID) {
		if option.CanSetZero(adminsession.FieldUID) || target.Uid != 0 {
			source.SetUID(target.Uid)
		}
	}
	if option.CanSetField(adminsession.FieldSessionKey) {
		if option.CanSetZero(adminsession.FieldSessionKey) || target.SessionKey != "" {
			source.SetSessionKey(target.SessionKey)
		}
	}
	if option.CanSetField(adminsession.FieldExpires) {
		if option.CanSetZero(adminsession.FieldExpires) || target.Expires != 0 {
			source.SetExpires(target.Expires)
		}
	}
	if option.CanSetField(adminsession.FieldIsRevoked) {
		if option.CanSetZero(adminsession.FieldIsRevoked) || target.IsRevoked {
			source.SetIsRevoked(target.IsRevoked)
		}
	}
	if option.CanSetField(adminsession.FieldDeviceInfo) {
		if option.CanSetZero(adminsession.FieldDeviceInfo) || target.DeviceInfo != "" {
			source.SetDeviceInfo(target.DeviceInfo)
		}
	}
	if option.CanSetField(adminsession.FieldIPAddress) {
		if option.CanSetZero(adminsession.FieldIPAddress) || target.IpAddress != "" {
			source.SetIPAddress(target.IpAddress)
		}
	}
	return source
}

func UpdateOneAdminSession(source *ent.AdminSessionUpdateOne, target *entpb.AdminSession, options ...bind.Option) *ent.AdminSessionUpdateOne {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(adminsession.FieldIsRevoked) {
		if option.CanSetZero(adminsession.FieldIsRevoked) || target.IsRevoked {
			source.SetIsRevoked(target.IsRevoked)
		}
	}
	if option.CanSetField(adminsession.FieldDeviceInfo) {
		if option.CanSetZero(adminsession.FieldDeviceInfo) || target.DeviceInfo != "" {
			source.SetDeviceInfo(target.DeviceInfo)
		}
	}
	if option.CanSetField(adminsession.FieldIPAddress) {
		if option.CanSetZero(adminsession.FieldIPAddress) || target.IpAddress != "" {
			source.SetIPAddress(target.IpAddress)
		}
	}
	return source
}

func CreateUser(source *ent.UserCreate, target *sharedv1.User, options ...bind.Option) *ent.UserCreate {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(user.FieldID) {
		if option.CanSetZero(user.FieldID) || target.Id != 0 {
			source.SetID(target.Id)
		}
	}
	if option.CanSetField(user.FieldUsername) {
		if option.CanSetZero(user.FieldUsername) || target.Username != "" {
			source.SetUsername(target.Username)
		}
	}
	if option.CanSetField(user.FieldAvatar) {
		if option.CanSetZero(user.FieldAvatar) || target.Avatar != "" {
			source.SetAvatar(target.Avatar)
		}
	}
	return source
}

func UpdateOneUser(source *ent.UserUpdateOne, target *sharedv1.User, options ...bind.Option) *ent.UserUpdateOne {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(user.FieldUsername) {
		if option.CanSetZero(user.FieldUsername) || target.Username != "" {
			source.SetUsername(target.Username)
		}
	}
	if option.CanSetField(user.FieldAvatar) {
		if option.CanSetZero(user.FieldAvatar) || target.Avatar != "" {
			source.SetAvatar(target.Avatar)
		}
	}
	return source
}

func CreateKeyValueStore(source *ent.KeyValueStoreCreate, target *entpb.KeyValueStore, options ...bind.Option) *ent.KeyValueStoreCreate {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(keyvaluestore.FieldKey) {
		if option.CanSetZero(keyvaluestore.FieldKey) || target.Key != "" {
			source.SetKey(target.Key)
		}
	}
	if option.CanSetField(keyvaluestore.FieldValue) {
		if option.CanSetZero(keyvaluestore.FieldValue) || target.Value != nil {
			source.SetValue(target.Value)
		}
	}
	return source
}

func UpdateOneKeyValueStore(source *ent.KeyValueStoreUpdateOne, target *entpb.KeyValueStore, options ...bind.Option) *ent.KeyValueStoreUpdateOne {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(keyvaluestore.FieldKey) {
		if option.CanSetZero(keyvaluestore.FieldKey) || target.Key != "" {
			source.SetKey(target.Key)
		}
	}
	if option.CanSetField(keyvaluestore.FieldValue) {
		if option.CanSetZero(keyvaluestore.FieldValue) || target.Value != nil {
			source.SetValue(target.Value)
		}
	}
	return source
}

func UpsertOneKeyValueStore(source *ent.KeyValueStoreUpsertOne, target *entpb.KeyValueStore, options ...bind.Option) *ent.KeyValueStoreUpsertOne {
	option := bind.NewBindOptions(options...)
	if option.CanSetField(keyvaluestore.FieldKey) {
		if option.CanSetZero(keyvaluestore.FieldKey) || target.Key != "" {
			source.SetKey(target.Key)
		}
	}
	if option.CanSetField(keyvaluestore.FieldValue) {
		if option.CanSetZero(keyvaluestore.FieldValue) || target.Value != nil {
			source.SetValue(target.Value)
		}
	}
	return source
}
