// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-sphere/sphere-layout/internal/biz/task/conncleaner"
	"github.com/go-sphere/sphere-layout/internal/biz/task/dashinit"
	"github.com/go-sphere/sphere-layout/internal/config"
	"github.com/go-sphere/sphere-layout/internal/pkg/dao"
	"github.com/go-sphere/sphere-layout/internal/pkg/database/client"
	api2 "github.com/go-sphere/sphere-layout/internal/server/api"
	dash2 "github.com/go-sphere/sphere-layout/internal/server/dash"
	file2 "github.com/go-sphere/sphere-layout/internal/server/file"
	"github.com/go-sphere/sphere-layout/internal/service/api"
	"github.com/go-sphere/sphere-layout/internal/service/dash"
	"github.com/go-sphere/sphere/cache/memory"
	"github.com/go-sphere/sphere/core/boot"
	"github.com/go-sphere/sphere/server/service/file"
)

// Injectors from wire.go:

func NewApplication(conf *config.Config) (*boot.Application, error) {
	dashConfig := conf.Dash
	localFileServiceConfig := conf.Local
	fileServer, err := file.NewLocalFileService(localFileServiceConfig)
	if err != nil {
		return nil, err
	}
	clientConfig := conf.Database
	entClient, err := client.NewDataBaseClient(clientConfig)
	if err != nil {
		return nil, err
	}
	daoDao := dao.NewDao(entClient)
	v := memory.NewByteCache()
	service := dash.NewService(daoDao, v, fileServer)
	web := dash2.NewWebServer(dashConfig, fileServer, service)
	apiConfig := conf.API
	apiService := api.NewService(daoDao, v, fileServer)
	apiWeb := api2.NewWebServer(apiConfig, fileServer, apiService)
	fileConfig := conf.File
	fileWeb, err := file2.NewWebServer(fileConfig, fileServer)
	if err != nil {
		return nil, err
	}
	dashInitialize := dashinit.NewDashInitialize(daoDao)
	connectCleaner := conncleaner.NewConnectCleaner(daoDao, v)
	application := newApplication(web, apiWeb, fileWeb, dashInitialize, connectCleaner)
	return application, nil
}
